### ISSUE TITLE
Datasources are not registered for WAR-based application

### ISSUE THREAD

**Issue by mchugunov** [wildfly-swarm/wildfly-swarm#101]
In a war-based swarm application I declare datasources as follows:

```
public static void main(String[] args) throws Exception {
        Container container = new Container()
                .subsystem(new DatasourcesFraction()
                                   .driver(new Driver("postgres")
                                                   .datasourceClassName("org.postgresql.Driver")
                                                   .xaDatasourceClassName("org.postgresql.xa.PGXADataSource")
                                                   .module("org.postgresql"))
                                   .datasource(new Datasource("DataSource")
                                                       .driver("postgres")
                                                       .connectionURL("jdbc:postgresql://localhost:5432/db")
                                                       .authentication("postgres", "postgres")
                                   )
                )
                .subsystem(new TransactionsFraction());

        container.start();
}
```

In pom.xml I declare that this class should be considered as application's mainClass:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-war-plugin</artifactId>
    <configuration>
        <archive>
            <manifest>
                <mainClass>com.project.emptywar.Main</mainClass>
            </manifest>
        </archive>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <packagingExcludes>WEB-INF/lib/wildfly-swarm-*.jar</packagingExcludes>
    </configuration>
</plugin>
```

While deploying I see that postgresql driver is loaded:

```
INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-6) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 9.4)
```

but I cannot access DataSource via JNDI inside deployed web-application.

The same configuration of Main class (that is referenced as mainClass in wildlfly-swarm-plugin configuration) for JAR-based application results in registered datasource:

```
INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 14) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-8) WFLYJCA0018: Started Driver service with driver-name = h2
...
INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0001: Bound data source [java:jboss/datasources/DataSource]
...
````

**Comment by emag** [comment]
Since you use main method, it has to be jar based application.

And, maybe you need some files(module.xml, provided-dependencies.txt).

``` sh
src/main/resources
├── modules
│   └── org
│       └── postgresql
│           └── main
│               └── module.xml
├── morecat
│   ├── git.properties
│   └── version.properties
└── provided-dependencies.txt
```

My project perhaps helps you. I also use PostgreSQL :)

https://github.com/emag/morecat/tree/1.0.0-update/morecat-api
https://github.com/emag/morecat/tree/1.0.0-update/morecat-api/src/main/resources

**Comment by mchugunov** [comment]
Thank you for a prompt reply, @emag. But does it mean that WAR-based applications are inconfigurable? Swarm docs (https://github.com/wildfly-swarm/wildfly-swarm#write-your-own-main) say that it is possible to reconfigure WAR-based application using ```main``` method

**Comment by emag** [comment]
Sorry, I misunderstood.

Umm, it seems there is no sample war based configured datasource application using maven-war-plugin + manifest(having main)...

Any idea @bobmcwhirter  @kenfinnigan ?

**Comment by bobmcwhirter** [comment]
Later version of swarm uses mainClass config in the swarm plugin instead of the war plugin, so that we can support wildfly-swarm:run and know what to run. 



--

**Comment by mchugunov** [comment]
@bobmcwhirter, I've pulled the last revision from wildfly-swarm/master, rebuilt it using ```mvn clean install``` and then rebuilt my application with following changes:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-war-plugin</artifactId>
    <configuration>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <packagingExcludes>WEB-INF/lib/wildfly-swarm-*.jar</packagingExcludes>
    </configuration>
</plugin>
<plugin>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>wildfly-swarm-plugin</artifactId>
    <version>${version.wildfly-swarm}</version>
    <configuration>
        <mainClass>com.project.emptywar.Main</mainClass>
    </configuration>
    <executions>
        <execution>
            <goals>
			    <goal>package</goal>
		    </goals>
        </execution>
    </executions>
</plugin>
```

After running  application ```java -jar kernel-pack-war\target\kernel-pack-war-swarm.jar``` I get 

```
Exception in thread "main" java.lang.ClassNotFoundException: com.project.emptywar.Main from [Module "org.wildfly.swarm.bootstrap:main" from BootModuleLoader@4f8e5cde for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@504bae78, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@3b764bce, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@759ebb3d, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@484b61fc]]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:51)
```

**Comment by bobmcwhirter** [comment]
This is weird.  Do you have a repo we can play with to try to debug?

**Comment by mchugunov** [comment]
Sure, https://github.com/mchugunov/wildfly-swarm-emptywar.git

**Comment by kenfinnigan** [comment]
My current understanding, as well as what we have with some examples, is that a `war` packaging type prevents the use of an overriding `Main` class.

If you want to override `Main`, then packaging type `jar` is needed.

Not to say it may not be possible to make a `Main` override work with `war` packaging, just that right now that won't work.

**Comment by bobmcwhirter** [comment]
We should be able to allow a main() from within a .war.  I'll see what we can do.

**Comment by helio-frota** [comment]
Hi, 

Using the `alpha5` got the following results:

1) Running from IDE main class the DataSource is registered but can't access index.jsp.
2) Running from mvn wildfly-swarm:run the DataSource is not registered but we can access index.jsp.

https://github.com/helio-frota/wildfly-swarm-war-datasource

**Comment by emag** [comment]
@helio-frota 
I think `index.jsp` should be treated as WebResource.

I changed some your code, and it seems it works. And, in Alpha5, index.jsp has to be under `resource` dir(classpath).

``` diff
$ git diff
diff --git a/pom.xml b/pom.xml
index 2708146..b41f551 100644
--- a/pom.xml
+++ b/pom.xml
@@ -7,7 +7,7 @@
     <groupId>org.esmerilprogramming</groupId>
     <artifactId>wildfly-swarm-war-datasource</artifactId>
     <version>0.0.1-SNAPSHOT</version>
-    <packaging>war</packaging>
+    <packaging>jar</packaging>
 
     <properties>
         <version.wildfly-swarm>1.0.0.Alpha5</version.wildfly-swarm>
diff --git a/src/main/java/org/esmerilprogramming/Main.java b/src/main/java/org/esmerilprogramming/Main.java
index 84361eb..711af80 100644
--- a/src/main/java/org/esmerilprogramming/Main.java
+++ b/src/main/java/org/esmerilprogramming/Main.java
@@ -1,6 +1,7 @@
 package org.esmerilprogramming;
 
 import org.jboss.shrinkwrap.api.ShrinkWrap;
+import org.jboss.shrinkwrap.api.asset.ClassLoaderAsset;
 import org.wildfly.swarm.config.datasources.DataSource;
 import org.wildfly.swarm.container.Container;
 import org.wildfly.swarm.datasources.DatasourcesFraction;
@@ -31,6 +32,8 @@ public class Main {
         container.fraction(new TransactionsFraction());
 
         WARArchive war = ShrinkWrap.create(WARArchive.class);
+        war.addAsWebResource(new ClassLoaderAsset("index.jsp", Main.class.getClassLoader()), "index.jsp");
+        
         container.start().deploy(war);
 
         Thread.sleep(1500);
```

``` sh
$ curl localhost:8080/index.jsp



<html>
<body>
<h2>Hail !</h2>
DataSource

</body>
</html>%        
```

**Comment by helio-frota** [comment]
@emag thanks for the diff + info !
I was trying to play with 'war + datasources + mysql' but without success for now (alpha5).

**Comment by kenfinnigan** [comment]
As part of a migration to JIRA for issue tracking, this issue has been moved to https://issues.jboss.org/browse/SWARM-111
