### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by helio-frota** [wildfly-swarm/wildfly-swarm#104]
hi all ,
exists a 'wildfly-swarm' irc channel for quick feedbacks ?
thanks
[INFO] WildFly Swarm: Naming Test ......................... FAILURE [  6.134 s]

**Comment by helio-frota** [comment]
[Stack here](https://gist.github.com/helio-frota/0e1a171c633a713870a0)

**Comment by kenfinnigan** [comment]
Is this with the latest HEAD?

I know we've got issues in CI at the moment that @bobmcwhirter is looking into

**Comment by kenfinnigan** [comment]
We are usually on https://www.hipchat.com/gW90m6pIs which is the WildFly HipChat room

**Comment by helio-frota** [comment]
@kenfinnigan yes latest HEAD.
i'm 'eprogramming' , changed my github username btw...
hipchat is blocked here unfortunately : /

**Comment by emag** [comment]
Hmm, `mvn clean install` is OK, however, `mvn test` is failed(latest HEAD 32a8da3).

In my environment, it gets stuck in `org.wildfly.swarm.naming.NamingInVmTest`.

the part of stacktrace.

``` sh
"main" #1 prio=5 os_prio=0 tid=0x00007fb880008800 nid=0x6849 runnable [0x00007fb887cf1000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:1122)
	at java.io.File.listFiles(File.java:1207)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:358)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
	at org.jboss.modules.FileResourceLoader.buildIndex(FileResourceLoader.java:362)
...
```

[full stacktrace](https://gist.github.com/emag/940f9e2c92c0518d7383)

**Comment by helio-frota** [comment]
hi 

```java
System.out.println(readerReady);
```
prints out always false :

https://github.com/helio-frota/wildfly-swarm/commit/d68411b7abaff1924f1cf2b1c88c52215fd5291c

**Comment by helio-frota** [comment]
after the latest fetch from upstream :

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.971 s
[INFO] Finished at: 2015-08-12T16:41:47-03:00
[INFO] Final Memory: 279M/897M
[INFO] ------------------------------------------------------------------------

thanks !
