### ISSUE TITLE
Failure loading server modules

### ISSUE THREAD

**Issue by fmarchioni** [wildfly-swarm/wildfly-swarm#106]
Hi!
I'm trying to run the examples using the 1.0.0.Alpha4 release. Here is for example the output from a mvn package wildfly-swarm:run against the servlet example (using 1.0.0.Alpha4 instead of 1.0.0.Alpha5-SNAPSHOT):
org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/msc/main/module.xml  
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)  
        at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)  
        at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)  
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)  
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)  
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)  
        at org.jboss.modules.Module.addPaths(Module.java:1028)  
        at org.jboss.modules.Module.link(Module.java:1398)  
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)  
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)  
        at org.wildfly.swarm.bootstrap.util.Layout.getBootstrapClassLoader(Layout.java:90)  
        at org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder.findModule(ClasspathModuleFinder.java:25)  
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)  
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)  
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)  
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)  
        at org.wildfly.swarm.Swarm.main(Swarm.java:36)  
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.msc:jboss-msc:1.2.6.Final' (position: END_TAG seen ...es>\n  
  `<artifact name="org.jboss.msc:jboss-msc:1.2.6.Final"/>`... @34:63)  
 
Shouldn't it reference something like jboss-msc-X.X.X.Final.jar rather ?

**Comment by kenfinnigan** [comment]
I just checked out the Alpha4 released examples and wasn't able to reproduce the issue.

Are you running on JDK 8?

**Comment by fmarchioni** [comment]
Yes, indeed I had JAVA_HOME pointing to the JDK 1.8.
Thanks
