### ISSUE TITLE
Bean with @Singleton causes error on start

### ISSUE THREAD

**Issue by thuryn** [wildfly-swarm/wildfly-swarm#127]
2015-10-01 09:46:42,172 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed - address: (("deployment" => "276dc127-c203-4df6-b357-ecb92381f7b8.war")) - failure description: {"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"276dc127-c203-4df6-b357-ecb92381f7b8.war\".component.MembersRest.CREATE is missing [jboss.ejb3.singletonDefaultTimeout]"]}
2015-10-01 09:46:42,173 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "276dc127-c203-4df6-b357-ecb92381f7b8.war" was rolled back with the following failure message: {"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"276dc127-c203-4df6-b357-ecb92381f7b8.war\".component.MembersRest.CREATE is missing [jboss.ejb3.singletonDefaultTimeout]"]}
2

**Comment by bobmcwhirter** [comment]
Are you using Alpha4 of WildFly-Swarm, or built from HEAD?

**Comment by thuryn** [comment]
Alpha5, so probably HEAD

**Comment by bobmcwhirter** [comment]
In https://github.com/wildfly-swarm/wildfly-swarm/commit/c1343c10f6aef314d1431617d19b284cac855651 I've added a test for @Singleton beans.

This might've been broken up until mid-day yesterday due to our movement to wildfly-config-api.jar and it's generated API.

Here's what I've added:

```
@Singleton
public class MySingletonBean implements MySingleton {

    @PostConstruct
    public void postConstruct() {
        System.err.println( "constructed" );
    }

    @Override
    public void sayHowdy() {
        System.err.println( "howdy!" );
    }
}
```

And console output from the related https://github.com/wildfly-swarm/wildfly-swarm/blob/master/ejb/test/src/test/java/org/wildfly/swarm/ejb/EJBArqSingletonTest.java seems to indicate it's working:

```
INFO: WFLYEJB0473: JNDI bindings for session bean named 'MySingletonBean' in deployment unit 'deployment "2c4a1767-78e2-4447-8dca-5414edbe0217.jar"' are as follows:

	java:global/2c4a1767-78e2-4447-8dca-5414edbe0217/MySingletonBean!org.wildfly.swarm.ejb.MySingleton
	java:app/2c4a1767-78e2-4447-8dca-5414edbe0217/MySingletonBean!org.wildfly.swarm.ejb.MySingleton
	java:module/MySingletonBean!org.wildfly.swarm.ejb.MySingleton
	java:global/2c4a1767-78e2-4447-8dca-5414edbe0217/MySingletonBean
	java:app/2c4a1767-78e2-4447-8dca-5414edbe0217/MySingletonBean
	java:module/MySingletonBean
```

If you could verify with HEAD as of today, that'd be great.

**Comment by thuryn** [comment]
OK, I'll try it today.

**Comment by thuryn** [comment]
I cannot test it because I've got other errors in deployment after update from github and build:

2015-10-01 17:30:45,608 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.deployment.unit."ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type PermissionResolver with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private transient org.picketlink.internal.AbstractIdentity.permissionResolver
  at org.picketlink.internal.AbstractIdentity.permissionResolver(AbstractIdentity.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateCustomBean(Validator.java:189)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:520)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

2015-10-01 17:30:45,616 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed - address: (("deployment" => "ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war")) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type PermissionResolver with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private transient org.picketlink.internal.AbstractIdentity.permissionResolver
  at org.picketlink.internal.AbstractIdentity.permissionResolver(AbstractIdentity.java:0)
"}}
2015-10-01 17:30:45,618 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"ca8667d2-4215-4a02-b3dd-c91f3d3ddfd4.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type PermissionResolver with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private transient org.picketlink.internal.AbstractIdentity.permissionResolver
  at org.picketlink.internal.AbstractIdentity.permissionResolver(AbstractIdentity.java:0)
"}}

**Comment by bobmcwhirter** [comment]
This is weird.  Do you have a repository I can test against?

**Comment by thuryn** [comment]
no at the moment. I'll try to fix this exception by managing dependencies and will see.

**Comment by thuryn** [comment]
So I can confirm, it works fine right now. So it was bad luck that I checked out sources with error at first. So next what I need is infinispan cache.

**Comment by thuryn** [comment]
thanks for help a lot
