### ISSUE TITLE
Failed to resolve artifact 'org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0

### ISSUE THREAD

**Issue by myfear** [wildfly-swarm/wildfly-swarm#134]
Building this example works fine.
https://github.com/myfear/WildFlySwarmDockerSample

running it leads to:

D:\GitHub\WildFlySwarmDockerSample\target>java -jar swarm-sample-1.0-SNAPSHOT-swarm.jar
org.jboss.modules.ModuleLoadException: Error loading module from modules/javax/sql/api/main/module.xml
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
        at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
        at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
        at org.jboss.modules.Module.addPaths(Module.java:1071)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.util.Layout.getBootstrapClassLoader(Layout.java:90)
        at org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder.findModule(ClasspathModuleFinder.java:25)
        at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
        at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
        at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:49)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.
Final' (position: END_TAG seen ...g.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.1.0.Final"/>... @27:93)
        at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
        at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
        at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
        at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
        at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
        ... 17 more
Exception in thread "main" org.jboss.modules.ModuleNotFoundException: org.wildfly.swarm.logging:main
        at org.jboss.modules.Module.addPaths(Module.java:1042)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:49)

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: D:\Program Files\apache-maven-3.3.3\bin\..
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: d:\jdk1.8.0_60\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

It seems to be a windows related issue, because I can dockerize this example and run it.

**Comment by bobmcwhirter** [comment]
What version of -swarm are you using?  Beta4 release?  Beta5-SNAPSHOT built from git?

**Comment by myfear** [comment]
Last stable Alpha4.

**Comment by kenfinnigan** [comment]
Ok, this looks like it's because we upgraded to WF 10.0.0.Beta1 just before releasing Alpha4, but the version for javax.sql was not updated to match.

It was fixed when we upgraded to Beta2 shortly after releasing.

Building latest master should resolve it

**Comment by kenfinnigan** [comment]
Marking as resolved. @myfear, let me know if this solution wasn't correct.
