### ISSUE TITLE
m2repro not used

### ISSUE THREAD

**Issue by sDaniel** [wildfly-swarm/wildfly-swarm#154]
Even though org.jboss.ws.cxf:jbossws-cxf-resources:5.1.0.Final:wildfly1000 is present in the m2repro folder in the jar it's not used and running the jar fails when there is no internet connection and the dependency is not in the local repro. To reproduce:

```
// disconnect from the internet
$ rm -r ~/.m2/repository/org/jboss/ws/cxf/jbossws-cxf-resources 
# in ~/workspaces/tests/wildfly-swarm-examples/jpa-jaxrs-cdi((default)|11d17h6m|master)
$ java -jar target/wildfly-swarm-example-jpa-jaxrs-cdi-swarm.jar          
setting default Datasource to ExampleDS
tmpDir: /var/folders/gz/78zrjhvs0b103wxxkgfb913m0000gp/T/
14:56:31,773 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
14:56:31,963 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 2.0.0.CR8 "Kenny" starting
14:56:34,548 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([]): java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.weld
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1336)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:459)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349)
	at org.jboss.as.server.ServerService.boot(ServerService.java:392)
	at org.jboss.as.server.ServerService.boot(ServerService.java:365)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: WFLYCTL0311: Failed to load Extension module org.jboss.as.weld
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
	... 11 more
Caused by: java.lang.RuntimeException: WFLYCTL0311: Failed to load Extension module org.jboss.as.weld
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:143)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/as/webservices/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:32)
	at org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder.findModule(ClasspathModuleFinder.java:53)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1179)
	at org.jboss.modules.Module.addPaths(Module.java:1071)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.jboss.modules.Module.loadServiceFromCallerModuleLoader(Module.java:360)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:120)
	... 8 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.ws.cxf:jbossws-cxf-resources:5.1.0.Final:wildfly1000' (position: END_TAG seen ..."org.jboss.ws.cxf:jbossws-cxf-resources:5.1.0.Final:wildfly1000"/>... @36:90) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 20 more

14:56:34,560 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
14:56:34,569 ERROR [stderr] (main) java.lang.reflect.InvocationTargetException
14:56:34,569 INFO  [org.jboss.as.server] (Thread-3) WFLYSRV0220: Server shutdown has been requested.
14:56:34,570 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:56:34,570 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:56:34,571 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:56:34,571 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:483)
14:56:34,571 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:59)
14:56:34,572 ERROR [stderr] (main) Caused by: java.util.concurrent.ExecutionException: Operation failed
14:56:34,572 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
14:56:34,572 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
14:56:34,573 ERROR [stderr] (main) 	at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:113)
14:56:34,573 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:173)
14:56:34,573 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.start(Container.java:318)
14:56:34,573 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:59)
14:56:34,574 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:52)
14:56:34,574 ERROR [stderr] (main) 	... 5 more
14:56:34,575 ERROR [stderr] (main) Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
14:56:34,575 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
14:56:34,575 ERROR [stderr] (main) 	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
14:56:34,575 ERROR [stderr] (main) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
14:56:34,576 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
14:56:34,576 ERROR [stderr] (main) java.util.concurrent.ExecutionException: Operation failed
14:56:34,576 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
14:56:34,576 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
14:56:34,576 ERROR [stderr] (main) 	at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:113)
14:56:34,577 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:173)
14:56:34,578 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.start(Container.java:318)
14:56:34,578 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:59)
14:56:34,578 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:52)
14:56:34,579 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:56:34,579 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:56:34,579 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:56:34,579 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:483)
14:56:34,579 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:59)
14:56:34,580 ERROR [stderr] (main) Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
14:56:34,580 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
14:56:34,580 ERROR [stderr] (main) 	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
14:56:34,580 ERROR [stderr] (main) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
14:56:34,581 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
14:56:34,581 ERROR [stderr] (main) java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
14:56:34,581 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
14:56:34,581 ERROR [stderr] (main) 	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
14:56:34,581 ERROR [stderr] (main) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
14:56:34,581 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
14:56:34,594 INFO  [org.jboss.as] (MSC service thread 1-3) WFLYSRV0050: WildFly Core 2.0.0.CR8 "Kenny" stopped in 16ms
```

**Comment by aparkins** [comment]
I encountered this issue today as well. Investigating, it appears that Wildfly is trying to include this dependency in the packaged wildfly-swarm.jar, but has the dependency mislabeled:

service-swarm.jar\m2repo\org\jboss\ws\cxf\jbossws-cxf-resources\5.1.0.Final\jbossws-cxf-resources-wildfly1000-5.1.0.Final.jar

Whereas, it appears the inner jar should be jbossws-cxf-resources-5.1.0.Final-wildfly1000.jar

I have encountered the error because for whatever reason my configurations are unable to access the Maven Central repository during deployment, but a coworker of mine was able to deploy despite this because his environment was able to connect. The jar is still mislabeled for him, but a subsequent search through the repository gets the dependency and allows it to be deployed.

**Comment by bobmcwhirter** [comment]
Good catch!

--
Sent from my iPhone


On Nov 11, 2015, at 5:04 PM, Aric Parkinson <notifications@github.com>
wrote:

I encountered this issue today as well. Investigating, it appears that
Wildfly is trying to include this dependency in the packaged
wildfly-swarm.jar, but has the dependency mislabeled:

service-swarm.jar\m2repo\org\jboss\ws\cxf\jbossws-cxf-resources\5.1.0.Final\jbossws-cxf-resources-wildfly1000-5.1.0.Final.jar

Whereas, it appears the inner jar should be
jbossws-cxf-resources-5.1.0.Final-wildfly1000.jar

I have encountered the error because for whatever reason my configurations
are unable to access the Maven Central repository during deployment, but a
coworker of mine was able to deploy despite this because his environment
was able to connect. The jar is still mislabeled for him, but a subsequent
search through the repository gets the dependency and allows it to be
deployed.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/154#issuecomment-155923889>
.

**Comment by kenfinnigan** [comment]
As part of a migration to JIRA for issue tracking, this issue has been moved to https://issues.jboss.org/browse/SWARM-164
