### ISSUE TITLE
Run Swam in IDE

### ISSUE THREAD

**Issue by dansiviter** [wildfly-swarm/wildfly-swarm#163]
I've just tried running Swarm from my Eclipse so I can debug the code, and unfortunately dies with:

```
2015-11-19 12:27:53,035 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.0.0.CR8 "Kenny" started in 1410ms - Started 119 of 126 services (16 services are lazy, passive or on-demand)
2015-11-19 12:28:46,755 ERROR [stderr] (main) Exception in thread "main" java.lang.UnsupportedOperationException: JavaArchive spec does not support Libraries
2015-11-19 12:28:46,755 ERROR [stderr] (main) 	at org.wildfly.swarm.container.JARArchiveImpl.getLibraryPath(JARArchiveImpl.java:106)
2015-11-19 12:28:46,755 ERROR [stderr] (main) 	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibrary(ContainerBase.java:1704)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibraries(ContainerBase.java:1903)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibraries(ContainerBase.java:1916)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.DependenciesContainer.addAllDependencies(DependenciesContainer.java:32)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.DefaultJarDeploymentFactory.setupUsingMaven(DefaultJarDeploymentFactory.java:136)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.DefaultJarDeploymentFactory.setup(DefaultJarDeploymentFactory.java:76)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.DefaultJarDeploymentFactory.create(DefaultJarDeploymentFactory.java:52)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.createDefaultDeployment(Container.java:443)
2015-11-19 12:28:46,756 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.deploy(Container.java:337)
2015-11-19 12:28:46,757 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:60)
2015-11-19 12:28:46,757 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:52)
```

I would have thought this would be one of the first use-cases rather than having to bind remotely. If there is a way of doing this, can it be documented please?

**Comment by bobmcwhirter** [comment]
Are you trying one of our lives samples or have a repo I can test against
to reproduce?

--
Sent from my iPhone


On Nov 19, 2015, at 7:32 AM, dansiviter <notifications@github.com> wrote:

I've just tried running Swarm from my Eclipse so I can debug the code, and
unfortunately dies with:

2015-11-19 12:27:53,035 INFO  [org.jboss.as] (Controller Boot Thread)
WFLYSRV0025: WildFly Core 2.0.0.CR8 "Kenny" started in 1410ms -
Started 119 of 126 services (16 services are lazy, passive or
on-demand)
2015-11-19 12:28:46,755 ERROR [stderr] (main) Exception in thread
"main" java.lang.UnsupportedOperationException: JavaArchive spec does
not support Libraries
2015-11-19 12:28:46,755 ERROR [stderr] (main)   at
org.wildfly.swarm.container.JARArchiveImpl.getLibraryPath(JARArchiveImpl.java:106)
2015-11-19 12:28:46,755 ERROR [stderr] (main)   at
org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibrary(ContainerBase.java:1704)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibraries(ContainerBase.java:1903)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.jboss.shrinkwrap.impl.base.container.ContainerBase.addAsLibraries(ContainerBase.java:1916)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.DependenciesContainer.addAllDependencies(DependenciesContainer.java:32)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.DefaultJarDeploymentFactory.setupUsingMaven(DefaultJarDeploymentFactory.java:136)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.DefaultJarDeploymentFactory.setup(DefaultJarDeploymentFactory.java:76)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.DefaultJarDeploymentFactory.create(DefaultJarDeploymentFactory.java:52)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.Container.createDefaultDeployment(Container.java:443)
2015-11-19 12:28:46,756 ERROR [stderr] (main)   at
org.wildfly.swarm.container.Container.deploy(Container.java:337)
2015-11-19 12:28:46,757 ERROR [stderr] (main)   at
org.wildfly.swarm.Swarm.simpleMain(Swarm.java:60)
2015-11-19 12:28:46,757 ERROR [stderr] (main)   at
org.wildfly.swarm.Swarm.main(Swarm.java:52)

I would have thought this would be one of the first use-cases rather than
having to bind remotely. If there is a way of doing this, can it be
documented please?

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/163>.

**Comment by dansiviter** [comment]
I wish I could; I'm evaluating this with some code from my client and I can't expose that. Long and short of it is running `org.wildfly.swarm.Swarm` from within Ecilpse with the following dependencies:

* wildfly-swarm-logging
* wildfly-swarm-weld
* wildfly-swarm-ejb

No VM or program arguments passed in on Java 8_u66.

**Comment by bobmcwhirter** [comment]
Okie dokie. I'll try to reproduce and will put my discovery and questions
here. Thanks!

--
Sent from my iPhone


On Nov 19, 2015, at 7:44 AM, dansiviter <notifications@github.com> wrote:

I wish I could; I'm evaluating this with some code from my client and I
can't expose that. Long and short of it is running org.wildfly.swarm.Swarm
from within Ecilpse with the following dependencies:

   - wildfly-swarm-logging
   - wildfly-swarm-weld
   - wildfly-swarm-ejb

No VM or program arguments passed in on Java 8_u66.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/163#issuecomment-158046503>
.

**Comment by dansiviter** [comment]
Thanks. Sorry to be a pain. I'll do my best to answer any questions.

**Comment by bobmcwhirter** [comment]
No pain at all! I appreciate the bug report. Not everyone has code they can
share. Completely understandable.

--
Sent from my iPhone


On Nov 19, 2015, at 7:57 AM, dansiviter <notifications@github.com> wrote:

Thanks. Sorry to be a pain. I'll do my best to answer any questions.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/163#issuecomment-158049727>
.

**Comment by bobmcwhirter** [comment]
So, this is an implicit <packaging>jar</packaging> right?  And do you have some additional dependency (non-swarm) in the project?

I think the core problem here, which is definitely a bug, is in .jar deployments, we do a `.addAllDependencies()` which actually doesn't work as written for .jars.  For a .war, it'd add them to `WEB-INF/lib` of the .war.

I'll keep poking.

**Comment by bobmcwhirter** [comment]
Okay, so if this is a .jar with EJB/CDI components, as a .jar it can't have any external dependencies, can it?  I'm a little confused as to how to exactly reproduce this or the use-case.  The default `Swarm` `main(...)` should attempt to deploy the maven-build `.jar` as a single thing.

There is a bug where there's dependencies from `-swarm` attempting to be added to the `.jar`.  I'm removing `.addAllDependencies()` from our `JARArchive` but I hope I'm not missing some use-case where is reasonable and possible to add dependencies to a default `.jar` deployment.

**Comment by dansiviter** [comment]
To confirm the original example above is `jar`, but as it's not gone through the packaging phase it's not all in one at that point. An IDE won't perform that as it will use the POM to load the classes and not create an uber-`jar`.

So I had a go deploying as a war (and adding `wildfly-swarm-undertow` dependency) and that is successful. Therefore, I feel some common ground is needed so we can develop in an IDE (that respects the Maven Object Model) regardless of it being a uber-`jar` or not. Does that make sense?

**Comment by bobmcwhirter** [comment]
Right, I agree.

If we you were using regular WildFly (not WF-Swarm), and built a `.jar` and deployed it as usual, we'd have no dependencies, right?  Just the content of that exact maven-built `.jar`.

I'm actually pretty ignorant of EJB/CDI deployments outside of `.war` files, so if I'm missing something, let me know.

**Comment by dansiviter** [comment]
Yea, that sound about right. It just so happened that I tried a non-webapp (normally a Maven built `jar`) and it wouldn't start up in the IDE. Obviously I'd like it to seamlessly work in both uber-`jar` mode and IDE with little (read: none) setup so I can be as my most productive. :wink:

**Comment by kenfinnigan** [comment]
As part of a migration to JIRA for issue tracking, this issue has been moved to https://issues.jboss.org/browse/SWARM-173
