### ISSUE TITLE
JPA support

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#23]
I created a simple JAX-RS + JPA app.

https://github.com/emag/wildfly-swarm-quickstarts/tree/master/jaxrs-jpa

I use [@ PersistenceContext for injection EntityManager](https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-jpa/src/main/java/wildflyswarm/jaxrsjpa/domain/repository/EmployeeRepository.java#L17-L18) but not injected.
It seems it is needed JPA Fraction. In WildFly Distro, a single persistence unit  is automatically discovered.

I've got the following log.

``` sh
$ git clone https://github.com/emag/wildfly-swarm-quickstarts && cd wildfly-swarm-quickstarts/jaxrs-jpa/
$ mvn clean package && java -jar target/jaxrs-jpa-*-swarm.jar
...
2015-05-14 02:14:51,421 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."jaxrs-jpa-1.0.0.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."jaxrs-jpa-1.0.0.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: WFLYWELD0037: Error injecting persistence unit into CDI managed bean. Can't find a persistence unit named '' in deployment jaxrs-jpa-1.0.0.war for injection point private javax.persistence.EntityManager wildflyswarm.jaxrsjpa.domain.repository.EmployeeRepository.em
	at org.jboss.as.weld.services.bootstrap.WeldJpaInjectionServices.getScopedPUName(WeldJpaInjectionServices.java:111)
	at org.jboss.as.weld.services.bootstrap.WeldJpaInjectionServices.registerPersistenceContextInjectionPoint(WeldJpaInjectionServices.java:74)
	at org.jboss.weld.injection.ResourceInjectionFactory$PersistenceContextResourceInjectionProcessor.getResourceReferenceFactory(ResourceInjectionFactory.java:313)
	at org.jboss.weld.injection.ResourceInjectionFactory$PersistenceContextResourceInjectionProcessor.getResourceReferenceFactory(ResourceInjectionFactory.java:301)
	at org.jboss.weld.injection.ResourceInjectionFactory$ResourceInjectionProcessor.createFieldResourceInjection(ResourceInjectionFactory.java:207)
	at org.jboss.weld.injection.ResourceInjectionFactory$ResourceInjectionProcessor.createResourceInjections(ResourceInjectionFactory.java:182)
	at org.jboss.weld.injection.ResourceInjectionFactory.discoverType(ResourceInjectionFactory.java:405)
	at org.jboss.weld.injection.ResourceInjectionFactory.getResourceInjections(ResourceInjectionFactory.java:92)
	at org.jboss.weld.injection.producer.ResourceInjector.<init>(ResourceInjector.java:59)
	at org.jboss.weld.injection.producer.ResourceInjector.of(ResourceInjector.java:49)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.<init>(BeanInjectionTarget.java:62)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.createDefault(BeanInjectionTarget.java:46)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.chooseInjectionTarget(InjectionTargetFactoryImpl.java:128)
	at org.jboss.weld.manager.InjectionTargetFactoryImpl.createInjectionTarget(InjectionTargetFactoryImpl.java:87)
	at org.jboss.weld.bean.ManagedBean.<init>(ManagedBean.java:100)
	at org.jboss.weld.bean.ManagedBean.of(ManagedBean.java:80)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createManagedBean(AbstractBeanDeployer.java:264)
	at org.jboss.weld.bootstrap.BeanDeployer.createClassBean(BeanDeployer.java:228)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:78)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:75)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by smiklosovic** [comment]
I consider JAX-RS, JPA and CDI to be the absolute basics which should be supported fully. Without this functionality you can not do anything meaningful really ... Would you be so nice and support that please?

**Comment by kenfinnigan** [comment]
We welcome all PRs, especially for additional functionality!

As we're working on other tasks, it's the fastest way to enable new functionality sooner.

Thanks
Ken

**Comment by emag** [comment]
@kenfinnigan  Thanks you for your reply. OK, I'll try it :)

**Comment by arun-gupta** [comment]
JPA support is very essential, and would love to see this coming through.

**Comment by emag** [comment]
Now I'm working on creating JPA Fraction and I've got a problem.

In using WildFly-Swarm, you must create a class has main() for setting datasource(e.g. [example-datasource](https://github.com/wildfly-swarm/example-datasource-subsystem/blob/master/src/main/java/org/wildfly/swarm/examples/ds/subsystem/Main.java#L19-L27)),  the application packaging must be `jar` and, -Swarm will transform the app from `jar` to `war`.

When `PersistenceUnitParseProcessor` parse a `persistence.xml` included the app, it checks the app packaging(deployment) type. As mentioned above,  your app deployment type is `war` so PersistenceUnitParseProcessor treats your app as war deployment and checks `/your-app.war/WEB-INF/classes/META-INF/persistence.xml`. Thus, persistence.xml is taken as not existing.

Any idea?

## related code

* https://github.com/wildfly/wildfly/blob/9.0.0.CR1/jpa/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java#L75
* https://github.com/wildfly/wildfly/blob/9.0.0.CR1/jpa/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java#L89

* https://github.com/wildfly/wildfly/blob/9.0.0.CR1/jpa/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java#L134

**Comment by kenfinnigan** [comment]
@emag, could you provide a link to your current code?

**Comment by emag** [comment]
@kenfinnigan 

https://github.com/emag/wildfly-swarm/tree/add-jpa-fraction-spike/fractions/jpa

And, I'm going to remove [some codes](https://github.com/emag/wildfly-swarm/blob/add-jpa-fraction-spike/fractions/jpa/src/main/java/org/wildfly/swarm/jpa/JpaFraction.java#L38-L45) because these are not resource but attributes.

**Comment by bobmcwhirter** [comment]
Your app can be natively a war also. See the example-servlet?

--

**Comment by emag** [comment]
@bobmcwhirter If I package my app as `war`, how can I set datasources ?

**Comment by arun-gupta** [comment]
Sweet, sample code?

**Comment by kenfinnigan** [comment]
@arun-gupta was about to email you!

https://github.com/wildfly-swarm/example-jpa-servlet

So for the moment i've only tested with servlet, but should be easy enough to create examples with CDI and JAX-RS now it's working

**Comment by bobmcwhirter** [comment]
All requires HEAD of wildfly-swarm built from GitHub at the moment.

**Comment by arun-gupta** [comment]
Exciting times, will play with it!

**Comment by arun-gupta** [comment]
#35 is blocking to test this functionality.

**Comment by emag** [comment]
@kenfinnigan  Awsome! I apply your commit and it works! 

And, I use subsystem version like example-datasource-subsystem. perfectly works :)

https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi-jpa/src/main/java/wildflyswarm/jaxrscdijpa/App.java#L22-L31
