### ISSUE TITLE
ClassNotFoundException: javax.sql.DataSource with Flyway

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#42]
I've tried WildFly Swarm + [Flyway](http://flywaydb.org/), which is database migration framework.

https://github.com/emag/example-jpa-jaxrs-cdi-flyway

And I've got `ClassNotFoundException: javax.sql.DataSource`.

It looks like https://github.com/flyway/flyway/issues/118 (OSGi environemnt) , but Flyway side was already fixed.

Any idea?

``` sh
$ git clone https://github.com/emag/example-jpa-jaxrs-cdi-flyway && cd example-jpa-jaxrs-cdi-flyway
$ mvn clean package && java -jar target/wildfly-swarm-example-jpa-jaxrs-cdi-flyway-1.0.0.Beta1-SNAPSHOT-swarm.jar
...
2015-06-04 00:10:32,925 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javax/sql/DataSource
	at org.wildfly.swarm.examples.jpa.DBMigrationInvoker.contextInitialized(DBMigrationInvoker.java:22)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:195)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:86)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:71)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
Caused by: java.lang.ClassNotFoundException: javax.sql.DataSource from [Module "APP:dependencies" from BootModuleLoader@4cdbe50f for finders [org.wildfly.swarm.bootstrap.modules.JBossModulesBootstrapModuleFinder@66d33a, org.wildfly.swarm.bootstrap.modules.JBossMSCBootstrapModuleFinder@7cf10a6f, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@6debcae2, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@5ba23b66]]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	... 10 more

2015-06-04 00:10:32,929 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed - address: (("deployment" => "b132e5e7-ab95-496c-89eb-4ce056b0d7c6.war")) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: Failed to start service
    Caused by: java.lang.NoClassDefFoundError: javax/sql/DataSource
    Caused by: java.lang.ClassNotFoundException: javax.sql.DataSource from [Module \"APP:dependencies\" from BootModuleLoader@4cdbe50f for finders [org.wildfly.swarm.bootstrap.modules.JBossModulesBootstrapModuleFinder@66d33a, org.wildfly.swarm.bootstrap.modules.JBossMSCBootstrapModuleFinder@7cf10a6f, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@6debcae2, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@5ba23b66]]"}}
2015-06-04 00:10:32,932 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "b132e5e7-ab95-496c-89eb-4ce056b0d7c6.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: Failed to start service
    Caused by: java.lang.NoClassDefFoundError: javax/sql/DataSource
    Caused by: java.lang.ClassNotFoundException: javax.sql.DataSource from [Module \"APP:dependencies\" from BootModuleLoader@4cdbe50f for finders [org.wildfly.swarm.bootstrap.modules.JBossModulesBootstrapModuleFinder@66d33a, org.wildfly.swarm.bootstrap.modules.JBossMSCBootstrapModuleFinder@7cf10a6f, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@6debcae2, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@5ba23b66]]"}}
...
```

While normal war deployment, it works.

1. Run WildFly 9.0.0.CR1
2. Chage`jar` to `war` in [pom.xml](https://github.com/emag/example-jpa-jaxrs-cdi-flyway/blob/master/pom.xml#L34-L35)
3. `mvn clean package wildfly:deploy`

``` sh
00:04:17,991 INFO  [org.flywaydb.core.internal.util.VersionPrinter] (MSC service thread 1-14) Flyway 3.2.1 by Boxfuse
00:04:18,000 INFO  [org.flywaydb.core.internal.dbsupport.DbSupportFactory] (MSC service thread 1-14) Database: jdbc:h2:mem:test (H2 1.3)
00:04:18,041 INFO  [org.flywaydb.core.internal.command.DbValidate] (MSC service thread 1-14) Validated 2 migrations (execution time 00:00.015s)
00:04:18,063 INFO  [org.flywaydb.core.internal.metadatatable.MetaDataTableImpl] (MSC service thread 1-14) Creating Metadata table: "PUBLIC"."schema_version"
00:04:18,074 INFO  [org.flywaydb.core.internal.command.DbMigrate] (MSC service thread 1-14) Current version of schema "PUBLIC": << Empty Schema >>
00:04:18,075 INFO  [org.flywaydb.core.internal.command.DbMigrate] (MSC service thread 1-14) Migrating schema "PUBLIC" to version 1 - create schema
00:04:18,088 INFO  [org.flywaydb.core.internal.command.DbMigrate] (MSC service thread 1-14) Migrating schema "PUBLIC" to version 1.1 - import initial data
00:04:18,095 INFO  [org.flywaydb.core.internal.command.DbMigrate] (MSC service thread 1-14) Successfully applied 2 migrations to schema "PUBLIC" (execution time 00:00.033s).
```

``` sh
$ curl localhost:8080/wildfly-swarm-example-jpa-jaxrs-cdi-flyway-1.0.0.Beta1-SNAPSHOT/       
[{"id":1,"name":"Penny"},{"id":2,"name":"Sheldon"},...}]
```

**Comment by kenfinnigan** [comment]
It should be coming from the JDK, so not sure why it can't be found

**Comment by bobmcwhirter** [comment]
It's in the JDK but jboss-modules still controls it.

It's available if you have javax.api:main module included.  

You might have to at least include the wildfly-swarm-datasources dependency just to pull in that portion of the module tree.

**Comment by emag** [comment]
I added  wildfly-swarm-datasources dependency, but the same result(and, wildfly-swarm-jpa depends on it).

**Comment by bobmcwhirter** [comment]
Alrighty, we'll take a look at it.  I can't personally guarantee that it'll be today, but we'll definitely poke around.

**Comment by bobmcwhirter** [comment]
Now I see

```
rtException in service jboss.undertow.deployment.default-server.default-host./: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.util.logging.slf4j.Slf4jLogCreator.createLogger(Slf4jLogCreator.java:27)
	at org.flywaydb.core.internal.util.logging.LogFactory.getLog(LogFactory.java:67)
	at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
	at org.flywaydb.core.internal.util.logging.LogFactory.getLog(LogFactory.java:55)
	at org.flywaydb.core.Flyway.<clinit>(Flyway.java:63)
	at org.wildfly.swarm.examples.jpa.DBMigrationInvoker.contextInitialized(DBMigrationInvoker.java:22)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:195)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:86)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:71)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
```

**Comment by bobmcwhirter** [comment]
And I find that weird, since it's seeming detecting org.slf4j.Logger but then then failing to construct a LoggerFactory.

Flyway's POM denotes slf4j as optional, so maybe try including it as an explicit dependency in your app?

I'll try now and report back.

**Comment by bobmcwhirter** [comment]
Okay, I add some dependencies to your project:

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-simple</artifactId>
          <version>1.7.12</version>
        </dependency>
```

And now the error I get is a Flyway error.  Dunno if it's wf-swarm caused or not.

```
Caused by: java.lang.RuntimeException: org.flywaydb.core.api.FlywayException: Unable to scan for SQL migrations in location: classpath:db/migration
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:224)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:86)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.start(UndertowDeploymentService.java:71)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
Caused by: org.flywaydb.core.api.FlywayException: Unable to scan for SQL migrations in location: classpath:db/migration
	at org.flywaydb.core.internal.util.scanner.Scanner.scanForResources(Scanner.java:55)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:110)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:41)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:126)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:108)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:94)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:42)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:96)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:136)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:131)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:131)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1102)
	at org.flywaydb.core.Flyway.access$300(Flyway.java:62)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at org.wildfly.swarm.examples.jpa.DBMigrationInvoker.contextInitialized(DBMigrationInvoker.java:24)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:195)
	... 7 more
```

*NOTE* This is with unreleased Alpha3-SNAPSHOT on HEAD of wildfly-swarm.

**Comment by emag** [comment]
Awesome, it works!

> And now the error I get is a Flyway error. Dunno if it's wf-swarm caused or not.

Sorry, it's my fault. I need to add migration sqls in main().
