### ISSUE TITLE
Missing JDK class

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#46]
I can't use ZooKeeper with Wildfly Swarm because it depends on `javax.security.auth.login.LoginException` which I cannot get into the classloader through any conventional means
<pre>
2015-06-05 02:18:01,912 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
2015-06-05 02:18:01,912 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-06-05 02:18:01,912 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-06-05 02:18:01,912 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-06-05 02:18:01,912 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-06-05 02:18:01,913 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:59)
2015-06-05 02:18:01,913 ERROR [stderr] (main) Caused by: java.lang.NoClassDefFoundError: javax/security/auth/login/LoginException
2015-06-05 02:18:01,913 ERROR [stderr] (main) 	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:385)
2015-06-05 02:18:01,913 ERROR [stderr] (main) 	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:344)
2015-06-05 02:18:01,913 ERROR [stderr] (main) 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:447)
2015-06-05 02:18:01,913 ERROR [stderr] (main) 	at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:146)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.ConnectionState.reset(ConnectionState.java:218)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.ConnectionState.start(ConnectionState.java:102)
2015-06-05 02:18:01,914 ERROR [stderr] (main) 	at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:189)
2015-06-05 02:18:01,915 ERROR [stderr] (main) 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:248)
2015-06-05 02:18:01,915 ERROR [stderr] (main) 	at com.test.service.Application.main(Application.java:39)
2015-06-05 02:18:01,915 ERROR [stderr] (main) 	... 5 more
2015-06-05 02:18:01,915 ERROR [stderr] (main) Caused by: java.lang.ClassNotFoundException: javax.security.auth.login.LoginException from [Module "org.wildfly.swarm.bootstrap:main" from BootModuleLoader@7cf10a6f for finders [org.wildfly.swarm.bootstrap.modules.JBossModulesBootstrapModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.JBossMSCBootstrapModuleFinder@6debcae2, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@5ba23b66, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@2ff4f00f, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@c818063]]
2015-06-05 02:18:01,915 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
2015-06-05 02:18:01,916 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
2015-06-05 02:18:01,916 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
2015-06-05 02:18:01,916 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
2015-06-05 02:18:01,916 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
2015-06-05 02:18:01,916 ERROR [stderr] (main) 	... 17 more
</pre>

**Comment by emag** [comment]
Hmm, It's similar to #42. `javax.security.auth.login.LoginException` included in rt.jar.
