### ISSUE TITLE
ClassNotFoundException for org.objectweb.asm.Opcodes

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#52]
My JAX-RS fraction utilizing projects throw an exception on startup unless a direct dependency on `org.ow2.asm:asm` is declared in each project's pom.xml
<pre>
Exception in thread "main" java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.wildfly.swarm.bootstrap.Main.main(Main.java:59)
Caused by: java.lang.LinkageError: Failed to link org/wildfly/swarm/jaxrs/ApplicationFactory (Module "org.wildfly.swarm.bootstrap:main" from BootModuleLoader@4cdbe50f for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@66d33a, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@7cf10a6f, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@6debcae2])
  at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
  at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
  at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
  at org.jboss.modules.Module.loadModuleClass(Module.java:560)
  at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
  at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
  at org.wildfly.swarm.jaxrs.JAXRSDeployment.ensureApplication(JAXRSDeployment.java:69)
  at org.wildfly.swarm.jaxrs.JAXRSDeployment.getArchive(JAXRSDeployment.java:76)
  at com.test.service.Application.main(Application.java:35)
  ... 5 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/Opcodes
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
  at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
  ... 16 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Opcodes from [Module "org.wildfly.swarm.bootstrap:main" from BootModuleLoader@4cdbe50f for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@66d33a, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@7cf10a6f, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@7e0babb1, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@6debcae2]]
  at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
  at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
  at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
  ... 20 more
</pre>

**Comment by bobmcwhirter** [comment]
Can you point me to the project or gist your pom?

--

**Comment by kenfinnigan** [comment]
Is the JAX-RS fraction dependency defined with a scope of "provided" in the pom of the application?

**Comment by amannm** [comment]
Here's an example project which currently suffers from this issue.on my machine: https://github.com/amannm/wildfly-swarm-example

**Comment by amannm** [comment]
Ok that's it then, apparently I was using the outdated method of using `provided` scope and it was manifesting itself as these issues. Thanks
