### ISSUE TITLE
JAXRS test failed / OSX 10.10.3 / JDK 1.7.0_72

### ISSUE THREAD

**Issue by awi** [wildfly-swarm/wildfly-swarm#54]
When build Alpha3-SNAPSHOT (df99c4bc1) the following integration test failed:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.wildfly.swarm.integration.jaxrs.JAXRSTest
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.util.logging.LogManager$1.run(LogManager.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at java.util.logging.Logger.demandLogger(Logger.java:339)
	at java.util.logging.Logger.getLogger(Logger.java:393)
	at org.jboss.shrinkwrap.api.ConfigurationBuilder.<clinit>(ConfigurationBuilder.java:51)
	at org.wildfly.swarm.container.Container.createShrinkWrapDomain(Container.java:59)
	at org.wildfly.swarm.container.Container.<init>(Container.java:45)
	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:21)
	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:16)
	at org.wildfly.swarm.integration.jaxrs.JAXRSTest.testSimple(JAXRSTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Jun 12, 2015 8:08:55 PM org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.2.4.Final
Jun 12, 2015 8:08:55 PM org.jboss.as.server.ApplicationServerService start
INFO: WFLYSRV0049: WildFly Core 1.0.0.CR1 "Kenny" starting
Jun 12, 2015 8:08:57 PM org.jboss.as.controller.AbstractOperationContext executeStep
ERROR: WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([])
java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.logging
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:803)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:601)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:354)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:330)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1183)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:429)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:327)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:313)
	at org.jboss.as.server.ServerService.boot(ServerService.java:381)
	at org.jboss.as.server.ServerService.boot(ServerService.java:356)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
	... 12 more
Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:144)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:131)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

Jun 12, 2015 8:08:57 PM org.jboss.as.server.ServerService boot
FATAL: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.

**Comment by bobmcwhirter** [comment]
JDK 8 is required. I bet you're using 7. 

--

**Comment by kenfinnigan** [comment]
I've just pushed an update to force building with JDK 8, and I'm pretty sure this issue is specific to JDK 7.
Please reopen if that's not the case

**Comment by awi** [comment]
Yep, builds with Java 8 on OSX.
Would be great to add these maven properties to wildfly-swarm-examples, too
