### ISSUE TITLE
NullPointer when packaging a war

### ISSUE THREAD

**Issue by johnament** [wildfly-swarm/wildfly-swarm#55]
I'm getting this NPE when trying to package my war

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha3-SNAPSHOT:package (default) on project my-webapp: Execution default of goal org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha3-SNAPSHOT:package failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha3-SNAPSHOT:package failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.wildfly.swarm.plugin.PackageMojo.expandArtifact(PackageMojo.java:488)
	at org.wildfly.swarm.plugin.PackageMojo.addWildflySwarmBootstrapJar(PackageMojo.java:141)
	at org.wildfly.swarm.plugin.PackageMojo.execute(PackageMojo.java:118)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more

**Comment by kenfinnigan** [comment]
Can you gist your pom.xml?

**Comment by bobmcwhirter** [comment]
Can you gist your pom.xml?

Ultimately, mvn dependency:tree should pull in wildfly-swarm-bootstrap, which seems to not be in your hierarchy.

Typically at least one wildfly-swarm-something will cause the -bootstrap to get pulled.  Do you have -jaxrs or -undertow or some other wildfly-swarm-* dependency listed as a <scope>compile</scope> dependency in your pom?

**Comment by bobmcwhirter** [comment]
Related to #56.  Not actually a bug, and error message has been improved.  The actual fix is regarding #56.
