### ISSUE TITLE
Duplication of *-swarm-*.jar's for WAR projects

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#56]
At the moment there is a duplication of the *-swarm*.jar in `_bootstrap` and `WEB-INF/lib` when the project is of type `war`.

Need to figure out whether there's something we need to change in how WildFly Swarm dependencies are added to a project to preclude this, or add documentation on how to prevent it.

**Comment by neich** [comment]
Can be this the reason of a NPE that I'm getting when executing the swarm JAR after ```mvn package``` ?

```
Exception in thread "main" java.lang.NullPointerException
	at org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder.gatherJarsFromJar(BootstrapModuleFinder.java:58)
	at org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder.findModule(BootstrapModuleFinder.java:29)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
```

```mvn wildfly-swarm:run``` works fine. This is my [pom.xml](https://gist.github.com/neich/a53eed2334ec696c2820)

Thanks

**Comment by kenfinnigan** [comment]
@neich No. The stack trace indicates that the `org.wildfly.swarm.bootstrap` artifact can't be loaded.

Is this artifact present in the _bootstrap directory of the archive?

**Comment by bobmcwhirter** [comment]
@neich see #68

**Comment by eprogramming** [comment]
@kenfinnigan 
I can not reproduce this issue.
*wildfly-swarm-examples/jpa-servlet* is type war and no duplication here.

**Comment by kenfinnigan** [comment]
@eprogramming, it's no longer the case that they're in `_bootstrap` but they are now in the `m2repo` directory.

In essence the issue is that they are present within `WEB-INF/lib` when they serve no purpose being there.

**Comment by bobmcwhirter** [comment]
And they are there in your bare .war also (not the one inside the -swarm), where they absolutely serve no purpose.

**Comment by kenfinnigan** [comment]
I've been looking at this the past few days without much success.

The cleanest way to prevent the jars ending up in WEB-INF/lib is by them being `provided` scope, otherwise you need a very messy set of exclude definitions for the `maven-war-plugin` that a user must enter themselves.

The problem with this approach is that the `Swarm` main class, when a project doesn't have it's own main, or any dependencies of the `Container` in either case, such as logging, can not be found.

It's a quirk of Maven scopes that `provided` dependencies are not available in any `run` phase, as it presumes the libraries are provided by some container, but they are available in a `test` phase.

So, one possible solution I've found is that if the WildFly Swarm dependencies are `provided` scoped, we could provide a base test class, from a new module that a user could add as a test dependency, that uses `@Before` and `@After` to start/stop the container as `Swarm` does in its main.

This might be a nice way to provide a way for the user to write test methods, but it's a little quirky for actually running it to play with in a browser as you essentially need a test that loops indefinitely.

It's not ideal, but is this approach acceptable given that running from an IDE is used less than from command line?

Thoughts?

**Comment by eprogramming** [comment]
Using **fat-jar** :

1. Running `./gradlew clean wildfly-swarm-package` generates two files: `sampleproject.jar` (without dependencies **+-200kb**) and `sampleproject-swarm.jar` (with dependencies **+-80mb**) 

2. The file `sampleproject-unspecified.jar` (**+-200kb** without dependencies ) is created inside `_bootstrap` directory.

The `sampleproject-unspecified.jar` is the duplicated jar of this issue ?

**Comment by eprogramming** [comment]
Using fat-jar and gradle the one 'duplicated' is this file 'sampleproject-unspecified.jar'

![dup_jar](https://cloud.githubusercontent.com/assets/6443576/8687918/d319fd5c-2a6b-11e5-9e00-79b592a24c61.png)

**Comment by kenfinnigan** [comment]
@eprogramming it's really only an issue when building WARs, as all the dependencies are added to WEB-INF/lib of the WAR file that is normally built, which is not good as it's unnecessary, and they're also present in WEB-INF/lib of the WAR that is added to _bootstrap of the WildFly Swarm archive, which is duplication because they're also present in the m2repo

**Comment by kenfinnigan** [comment]
As part of a migration to JIRA for issue tracking, this issue has been moved to https://issues.jboss.org/browse/SWARM-66
