### ISSUE TITLE
Dependency injection issue

### ISSUE THREAD

**Issue by fbricon** [wildfly-swarm/wildfly-swarm#63]
So I'm trying to replace https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/jpa-jaxrs-cdi-shrinkwrap/src/main/java/org/wildfly/swarm/examples/jpa/EmployeeResource.java#L18 with

    @Inject 
    private EntityManager em;

where the entity manager is produced by another class : 

    public class Resources {
      @Produces
      @PersistenceContext
      private EntityManager em;
    }

similar to this [quickstart](https://github.com/wildfly/quickstart/blob/master/kitchensink-html5-mobile/src/main/java/org/jboss/as/quickstarts/html5_mobile/util/Resources.java) that I'm trying to port to use wildfly-swarm. 

After doing `deployment.getArchive().addClasses(Resources.class);`, when I start the main class I get : 

2015-06-19 15:06:04,943 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."57f698ba-63fe-4ce5-af6c-c955f09eb183.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."57f698ba-63fe-4ce5-af6c-c955f09eb183.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type EntityManager with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.wildfly.swarm.examples.jpa.EmployeeResource.em
  at org.wildfly.swarm.examples.jpa.EmployeeResource.em(EmployeeResource.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

2015-06-19 15:06:04,947 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed - address: (("deployment" => "57f698ba-63fe-4ce5-af6c-c955f09eb183.war")) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"57f698ba-63fe-4ce5-af6c-c955f09eb183.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"57f698ba-63fe-4ce5-af6c-c955f09eb183.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type EntityManager with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.wildfly.swarm.examples.jpa.EmployeeResource.em
  at org.wildfly.swarm.examples.jpa.EmployeeResource.em(EmployeeResource.java:0)
"}}
2015-06-19 15:06:04,949 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "57f698ba-63fe-4ce5-af6c-c955f09eb183.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"57f698ba-63fe-4ce5-af6c-c955f09eb183.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"57f698ba-63fe-4ce5-af6c-c955f09eb183.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type EntityManager with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.wildfly.swarm.examples.jpa.EmployeeResource.em
  at org.wildfly.swarm.examples.jpa.EmployeeResource.em(EmployeeResource.java:0)

I don't know if this is a WF-swarm bug or if I'm doing something wrong. Please advise. Thx.

**Comment by emag** [comment]
I added @ Dependant to Resources and it works.

``` java
package org.wildfly.swarm.examples.jpa;

import javax.enterprise.context.Dependent;
import javax.enterprise.inject.Produces;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Dependent
public class Resources {

  @Produces
  @PersistenceContext
  private EntityManager em;

}
```

But, when `em` ia added @ Dependent, it doesn't work. Since @ Depedent target includes FIELD, it should work.

**Comment by bobmcwhirter** [comment]
@fbricon So, when I ensured the deployment had a beans.xml, I had success.

I've added this to my Main.java:


        deployment.getArchive().addAsWebInfResource( new StringAsset("<beans xmlns=\"http://xmlns.jcp.org/xml/ns/javaee\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
                "    xsi:schemaLocation=\"\n" +
                "        http://xmlns.jcp.org/xml/ns/javaee\n" +
                "        http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd\" bean-discovery-mode=\"all\">\n" +
                "</beans>"), "beans.xml");

**Comment by bobmcwhirter** [comment]
Of course, I also added this:

        deployment.getArchive().addClass(Resources.class);

**Comment by bobmcwhirter** [comment]
I've added an example to the examples repo:

https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jpa-jaxrs-cdi-shrinkwrap2

If you could verify this is happy and close this issue when you're satisfied.

We could probably make it easier to add the minimal beans.xml via something better than a StringAsset.

**Comment by fbricon** [comment]
mmm I thought beans.xml was optional already in javaee7. guess I was wrong

**Comment by bobmcwhirter** [comment]
I only tried it because the QuickStart had one. 

--

**Comment by fbricon** [comment]
Works fine now, thanks @bobmcwhirter !

**Comment by emag** [comment]
@fbricon 

Yes. related spec.

https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_archive

> An implicit bean archive is any other archive which contains one or more bean classes with a bean defining annotation as defined in Bean defining annotations, or one or more session beans.

* implicit bean archive = no beans.xml
* bean defining annotation = javax.enterprise.context.{*Scoped, Dependant}

So, if you don't want to add beans.xml, you have to add some scoped annotation.
