### ISSUE TITLE
NPE when executing JAR file after mvn package with Alpha 3

### ISSUE THREAD

**Issue by neich** [wildfly-swarm/wildfly-swarm#68]
Hi,

I'm getting this null pointer exception error when I try to execute the packaged JAR:

```
Exception in thread "main" java.lang.NullPointerException
	at org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder.gatherJarsFromJar(BootstrapModuleFinder.java:58)
	at org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder.findModule(BootstrapModuleFinder.java:29)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
```

But ``mvn wildfly-swarm:run``` works fine. This is my [pom.xml](https://gist.github.com/neich/a53eed2334ec696c2820)

The _bootstrap directory of the -swarm.jar file only contains api-0.0.1.jar

Thanks

**Comment by kenfinnigan** [comment]
Can you gist the contents of the -swarm archive?

**Comment by neich** [comment]
Here it is:

https://gist.github.com/neich/8042a5bea7eab275780a

**Comment by neich** [comment]
I've produced a small project that reproduces the error. The problem seems to be this:

```
    <dependency>
      <groupId>com.thinkaurelius.titan</groupId>
      <artifactId>titan-core</artifactId>
      <version>0.9.0-M2</version>
    </dependency>
```
Here it is: https://github.com/neich/swarm-execution-error

It is really minimal, the above dependency and two small java files. 

```mvn wildfly-swarm:run``` works fine but ```mvn package && java -jar target/api-0.0.1-swarm.jar``` gives the error

**Comment by bobmcwhirter** [comment]
Okay, so we have a better error message now if it fails to find an artifact.

And we should do a better job of finding project artifacts/dependencies that require a classifier (the -indy on groovy-all in this case).

If you can try 1.0.0.Alpha4-SNAPSHOT from HEAD of wildfly-swarm, it should solve this problem.

**Comment by neich** [comment]
All working fine with 1.0.0.Alpha4-SNAPSHOT. Thanks !
