### ISSUE TITLE
Wildfly swarm and jRuby application build by maven

### ISSUE THREAD

**Issue by swistaczek** [wildfly-swarm/wildfly-swarm#70]
Hello,
I am trying to build complete executable JAR for web microservice (for future deployments on platforms like messos) for application written in Ruby. My goal is to combine **Ruby** web service (as application) with **undertow** web server and build so called **fat jar**. 

I found great pieces of code created community and tried to combine them together with varying results due to my lack of understanding Java ecosystem. Couple hours ago I have found *widfly-swarm* that suits my needs (and also by far exceeds them by embedding full JBoss application server) but after initial setup I found some issues described by following error:
```
[INFO] --- wildfly-swarm-plugin:1.0.0.Alpha3:run (default-cli) @ webservice ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/3.2.5/maven-plugin-api-3.2.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.2.5/maven-model-3.2.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.2.5/maven-artifact-3.2.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.0.M1/org.eclipse.sisu.plexus-0.3.0.M1.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/3.2.5/maven-plugin-api-3.2.5.jar (46 KB at 225.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar (49 KB at 243.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.2.5/maven-artifact-3.2.5.jar (54 KB at 252.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.0.M1/org.eclipse.sisu.plexus-0.3.0.M1.jar (196 KB at 722.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.2.5/maven-model-3.2.5.jar (158 KB at 493.8 KB/sec)
Exception in thread "main" org.jboss.modules.ModuleLoadError: Error loading module from modules/org/jboss/invocation/main/module.xml
	at org.jboss.modules.ModuleLoadException.toError(ModuleLoadException.java:74)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1384)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.runtime.container.RuntimeServer.<init>(RuntimeServer.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.wildfly.swarm.container.Container.createServer(Container.java:85)
	at org.wildfly.swarm.container.Container.<init>(Container.java:51)
	at org.wildfly.swarm.Swarm.main(Swarm.java:25)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.invocation:jboss-invocation:1.4.1.Final' (position: END_TAG seen ...rtifact name="org.jboss.invocation:jboss-invocation:1.4.1.Final"/>... @32:77)
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.getPaths(Module.java:1359)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
	... 15 more
```

Please check out repository https://github.com/swistaczek/wildfly-swarm-jruby for error reproducton and any future debbuging. 

Ps. I am not one 100% sure that I am using perfect tooling for given problem :smile:.

**Comment by bobmcwhirter** [comment]
What versions of maven and jruby are you using so that I may attempt to replicate?

--

**Comment by bobmcwhirter** [comment]
So, this is what I get, which seems like an app error, not a -swarm error:

```
eduardo:wildfly-swarm-jruby bob$ rmvn wildfly-swarm:run
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.M1/jetty-maven-plugin-9.3.0.M1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.M1/jetty-maven-plugin-9.3.0.M1.pom (6 KB at 9.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.3.0.M1/jetty-project-9.3.0.M1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.3.0.M1/jetty-project-9.3.0.M1.pom (35 KB at 152.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/23/jetty-parent-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/23/jetty-parent-23.pom (22 KB at 141.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.M1/jetty-maven-plugin-9.3.0.M1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.3.0.M1/jetty-maven-plugin-9.3.0.M1.jar (96 KB at 346.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/tomcat-maven-plugin/1.1/tomcat-maven-plugin-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/tomcat-maven-plugin/1.1/tomcat-maven-plugin-1.1.pom (9 KB at 58.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/27/mojo-parent-27.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/27/mojo-parent-27.pom (27 KB at 173.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/tomcat-maven-plugin/1.1/tomcat-maven-plugin-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/tomcat-maven-plugin/1.1/tomcat-maven-plugin-1.1.jar (58 KB at 348.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/wildfly/plugins/wildfly-maven-plugin/1.0.2.Final/wildfly-maven-plugin-1.0.2.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/wildfly/plugins/wildfly-maven-plugin/1.0.2.Final/wildfly-maven-plugin-1.0.2.Final.pom (16 KB at 99.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/wildfly/plugins/wildfly-maven-plugin/1.0.2.Final/wildfly-maven-plugin-1.0.2.Final.jar
Downloaded: https://repo.maven.apache.org/maven2/org/wildfly/plugins/wildfly-maven-plugin/1.0.2.Final/wildfly-maven-plugin-1.0.2.Final.jar (119 KB at 504.6 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building webservice 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> wildfly-swarm-plugin:1.0.0.Alpha3:run (default-cli) > package @ webservice >>>
[INFO]
[INFO] --- gem-maven-plugin:1.0.9:initialize (install gems) @ webservice ---
[INFO]
[INFO] --- gem-maven-plugin:1.0.9:sets (install gem sets for compile) @ webservice ---
[INFO] installing gem sets for compile scope into pkg/rubygems
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ webservice ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 1 resource to WEB-INF
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ webservice ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ webservice ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/bob/repos/wildfly-swarm-jruby/src/test/resources
[INFO] Copying 1254 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ webservice ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ webservice ---
[INFO]
[INFO] --- maven-war-plugin:2.2:war (default-war) @ webservice ---
[INFO] Packaging webapp
[INFO] Assembling webapp [webservice] in [/Users/bob/repos/wildfly-swarm-jruby/pkg/wildfly-swarm-jruby]
[INFO] Processing war project
[INFO] Copying webapp webResources [/Users/bob/repos/wildfly-swarm-jruby] to [/Users/bob/repos/wildfly-swarm-jruby/pkg/wildfly-swarm-jruby]
[INFO] Webapp assembled in [112 msecs]
[INFO] Building war: /Users/bob/repos/wildfly-swarm-jruby/pkg/wildfly-swarm-jruby.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO]
[INFO] <<< wildfly-swarm-plugin:1.0.0.Alpha3:run (default-cli) < package @ webservice <<<
[INFO]
[INFO] --- wildfly-swarm-plugin:1.0.0.Alpha3:run (default-cli) @ webservice ---
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.jar (49 KB at 292.9 KB/sec)
09:29:24,331 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.4.Final
09:29:24,514 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 1.0.0.CR6 "Kenny" starting
2015-06-24 09:29:25,073 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 10) WFLYNAM0001: Activating Naming Subsystem
2015-06-24 09:29:25,074 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 9) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
2015-06-24 09:29:25,095 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-9) WFLYUT0003: Undertow 1.2.7.Final starting
2015-06-24 09:29:25,095 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 7) WFLYUT0003: Undertow 1.2.7.Final starting
2015-06-24 09:29:25,099 INFO  [org.jboss.as.naming] (MSC service thread 1-15) WFLYNAM0003: Starting Naming Service
2015-06-24 09:29:25,119 INFO  [org.xnio] (MSC service thread 1-16) XNIO version 3.3.1.Final
2015-06-24 09:29:25,129 INFO  [org.xnio.nio] (MSC service thread 1-16) XNIO NIO Implementation Version 3.3.1.Final
2015-06-24 09:29:25,166 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-16) WFLYUT0012: Started server default-server.
2015-06-24 09:29:25,210 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0006: Undertow HTTP listener default listening on /0:0:0:0:0:0:0:0:8080
2015-06-24 09:29:25,286 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 1.0.0.CR6 "Kenny" started in 861ms - Started 56 of 62 services (13 services are lazy, passive or on-demand)
2015-06-24 09:29:26,737 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-12) WFLYSRV0027: Starting deployment of "a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war" (runtime-name: "a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war")
2015-06-24 09:29:27,724 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-9) WFLYUT0018: Host default-host starting
2015-06-24 09:29:27,854 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 6) INFO: jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b20 +jit [darwin-x86_64]
2015-06-24 09:29:27,855 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 6) INFO: using a shared (threadsafe!) runtime
2015-06-24 09:29:29,557 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 6) An exception happened during JRuby-Rack startup
no such file to load -- bundler/setup
--- System
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b20 +jit [darwin-x86_64]
Time: 2015-06-24 09:29:29 -0400
Server: WildFly 1.0.0.CR6 - 1.2.7.Final
jruby.home: classpath:/META-INF/jruby.home

--- Context Init Parameters:
gem.path = WEB-INF/classes
public.root = /
rack.env = production

--- Backtrace
LoadError: no such file to load -- bundler/setup
        require at org/jruby/RubyKernel.java:1072
        require at classpath:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
         (root) at uri:classloader://config.ru:6
  instance_eval at org/jruby/RubyBasicObject.java:1537
     initialize at classpath:/vendor/rack-1.5.2/rack/builder.rb:55
         (root) at uri:classloader://config.ru:1

--- RubyGems
Gem.dir: /Users/bob/.rvm/gems/jruby-1.7.19@wildfly-swarm-jruby
Gem.path:
/var/folders/sf/_mymxqxj4xncf0jqc9tv3p6w0000gn/T/wildfly-self-contained7352683489475042086.d/vfs/wildfly-swarm/wildfly-swarmc7840393a9c9c583/a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war-92dbdd26745b8dc5/contents/WEB-INF/classes
/Users/bob/.rvm/gems/jruby-1.7.19@wildfly-swarm-jruby
/Users/bob/.rvm/gems/jruby-1.7.19@global
Activated gems:

--- Bundler
undefined method `bundle_path' for Bundler:Module

--- JRuby-Rack Config
compat_version =
default_logger = org.jruby.rack.logging.StandardOutLogger@612bde29
equals = <error: >
err = org.jboss.stdio.StdioContext$2@7c436b57
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size =
initial_runtimes =
jms_connection_factory =
jms_jndi_properties =
logger = org.jruby.rack.logging.ServletContextLogger@6f641030
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size =
maximum_runtimes =
num_initializer_threads =
out = org.jboss.stdio.StdioContext$1@4fa0eac6
rackup =
rackup_path =
rewindable = true
runtime_arguments =
runtime_environment =
runtime_timeout_seconds =
serial_initialization = false
servlet_context = io.undertow.servlet.spec.ServletContextImpl@978323b
throw_init_exception = false

--- $LOAD_PATH:
/var/folders/sf/_mymxqxj4xncf0jqc9tv3p6w0000gn/T/wildfly-self-contained7352683489475042086.d/vfs/wildfly-swarm/wildfly-swarmc7840393a9c9c583/a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war-92dbdd26745b8dc5/contents/WEB-INF
uri:classloader:
classpath:/vendor/rack-1.5.2
classpath:/META-INF/jruby.home/lib/ruby/1.9/site_ruby
classpath:/META-INF/jruby.home/lib/ruby/shared
classpath:/META-INF/jruby.home/lib/ruby/1.9

2015-06-24 09:29:29,558 ERROR [io.undertow.servlet] (ServerService Thread Pool -- 6) ERROR: initialization failed: org.jruby.rack.RackInitializationException: no such file to load -- bundler/setup
	from org/jruby/RubyKernel.java:1072:in `require'
	from classpath:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
	from uri:classloader://config.ru:6:in `(root)'
	from org/jruby/RubyBasicObject.java:1537:in `instance_eval'
	from classpath:/vendor/rack-1.5.2/rack/builder.rb:55:in `initialize'
	from uri:classloader://config.ru:1:in `(root)'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:195)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- bundler/setup
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1072)
	at RUBY.require(classpath:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.(root)(uri:classloader://config.ru:6)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1537)
	at RUBY.initialize(classpath:/vendor/rack-1.5.2/rack/builder.rb:55)
	at RUBY.(root)(uri:classloader://config.ru:1)

2015-06-24 09:29:29,577 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 6) WFLYUT0021: Registered web context: /
2015-06-24 09:29:29,580 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war" (runtime-name : "a83d6ecb-9a70-4d9e-83e9-1615a46826f9.war")
```

**Comment by swistaczek** [comment]
@bobmcwhirter I am using JRuby 1.7.20, Maven 3.3.3. Make sure that you have enabled JRuby, then install deps from Gemfile (it installs maven-tools etc.) and then run rmvn wildfly-swarm:run.

```
rvm use jruby 1.7.20
bundle install
rmvn wildfly-swarm:run
````

**Comment by bobmcwhirter** [comment]
Okay, once I did `bundle install` it boots without error locally, but I get "NOT FOUND" at http://localhost:8080/

I am using Alpha4-SNAPSHOT from git for wildfly-swarm.  Dunno if that makes a difference or not.

```
[INFO] --- wildfly-swarm-plugin:1.0.0.Alpha3:run (default-cli) @ webservice ---
11:48:10,396 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.4.Final
11:48:10,580 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 1.0.0.CR6 "Kenny" starting
2015-06-24 11:48:11,156 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 10) WFLYNAM0001: Activating Naming Subsystem
2015-06-24 11:48:11,156 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 9) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
2015-06-24 11:48:11,175 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 7) WFLYUT0003: Undertow 1.2.7.Final starting
2015-06-24 11:48:11,175 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-10) WFLYUT0003: Undertow 1.2.7.Final starting
2015-06-24 11:48:11,177 INFO  [org.jboss.as.naming] (MSC service thread 1-11) WFLYNAM0003: Starting Naming Service
2015-06-24 11:48:11,196 INFO  [org.xnio] (MSC service thread 1-7) XNIO version 3.3.1.Final
2015-06-24 11:48:11,206 INFO  [org.xnio.nio] (MSC service thread 1-7) XNIO NIO Implementation Version 3.3.1.Final
2015-06-24 11:48:11,240 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0012: Started server default-server.
2015-06-24 11:48:11,288 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0006: Undertow HTTP listener default listening on /0:0:0:0:0:0:0:0:8080
2015-06-24 11:48:11,364 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 1.0.0.CR6 "Kenny" started in 871ms - Started 56 of 62 services (13 services are lazy, passive or on-demand)
2015-06-24 11:48:12,801 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0027: Starting deployment of "702c6c59-3d1a-4a0b-83a4-3f21c3884062.war" (runtime-name: "702c6c59-3d1a-4a0b-83a4-3f21c3884062.war")
2015-06-24 11:48:13,834 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-13) WFLYUT0018: Host default-host starting
2015-06-24 11:48:13,950 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 2) INFO: jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b20 +jit [darwin-x86_64]
2015-06-24 11:48:13,951 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 2) INFO: using a shared (threadsafe!) runtime
2015-06-24 11:48:16,164 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 2) WFLYUT0021: Registered web context: /
2015-06-24 11:48:16,167 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "702c6c59-3d1a-4a0b-83a4-3f21c3884062.war" (runtime-name : "702c6c59-3d1a-4a0b-83a4-3f21c3884062.war")
2015-06-24 11:48:26,794 INFO  [io.undertow.servlet] (default task-1) 0:0:0:0:0:0:0:1 -  [24/Jun/2015:11:48:26 -0400] "GET / " 404 18 0.0300
```

**Comment by bobmcwhirter** [comment]
Okay...

So, first, you need to ensure the `package` goal is called in the wildfly-swarm-plugin

```
plugin( 'org.wildfly.swarm:wildfly-swarm-plugin', '1.0.0.Alpha4-SNAPSHOT' ) do
  execute_goal( 'package', phase: 'package' )
end
```

This goal must be configured because when `wildfly-swarm:run` executes it follows the `package` phase, which in tern gathers all the required dependencies into your local maven repository.  Without this, `wildfly-swarm:run` would only work if you already had a fully-population maven repository (as I did originally).

Additionally, Alpha3 is broken in terms of some rmvn/ruby stuff, but I've started fixing it in HEAD (Alpha4-SNAPSHOT) of wildfly-swarm.git.  We erroneously assumed all project dependencies were `.jar` files, and of course, you have some `.gem` files.

I still get a `404/NOT FOUND` when I hit http://localhost:8080/, so I'm not sure what's up with that.

If you're willing to try building `wildfly-swarm` from HEAD and adjusting your `Mavenfile` to use 1.0.0.Alpha4-SNAPSHOT, feel free to add any further comments or discover on this issue.

I'll leave it open.

Thanks.

**Comment by bobmcwhirter** [comment]
In case you're not a Java guy, just clone the wildfly-swarm repository and run generic

`mvn install`

from the root.  It'll install 1.0.0.Alpha4-SNAPSHOT into your local repository.

**Comment by bobmcwhirter** [comment]
Ping?

**Comment by helio-frota** [comment]
hi @swistaczek 
the error continues with alpha5 released ?

**Comment by helio-frota** [comment]
hi all using alpha5 
getting different errors by running `rmvn wildfly-swarm:run`

![01](https://cloud.githubusercontent.com/assets/6443576/11115374/d8befb34-8909-11e5-8178-69ef807d13de.png)

full stack:
https://gist.github.com/helio-frota/e9df7045ebd67ac711f1

**Comment by kenfinnigan** [comment]
As part of a migration to JIRA for issue tracking, this issue has been moved to https://issues.jboss.org/browse/SWARM-80
