### ISSUE TITLE
Modify gradle plugin to create jar inside build/libs directory

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#81]
when using gradle 
'gradle clean build'
(similar to 'mvn clean package')
uses the build/libs directory as default place to the generated jar

currently the plugin creates the jar inside 'build' not 'build/libs'

**Comment by bobmcwhirter** [comment]
Ah thanks. That's the sort of convention I'm ignorant of. Easily fixable. 

--

**Comment by bobmcwhirter** [comment]
Also, changed the property from swarm.mainClass to swarm.mainClassName.

And if you're using the application plugin and have `mainClassName` defined at the root, we fall back to that if you don't have `swarm.mainClassName` defined.

**Comment by eprogramming** [comment]
great !

**Comment by bobmcwhirter** [comment]
@eprogramming so I'm about at my limit of Gradle stuff.  If you want to make changes/etc, I'll be glad to merge them (or give you commits directly).

**Comment by eprogramming** [comment]
@bobmcwhirter thanks very much for this feedback !
Also i'll try to contribute with others areas of wildfly-swarm of course.

**Comment by eprogramming** [comment]
@bobmcwhirter 
something get wrong 
after updating all...

1. Still creating the jar on build dir instead build/libs
2. now shows this error:

```
2015-07-06 17:53:41,570 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 1.0.0.CR6 "Kenny" started in 1742ms - Started 63 of 69 services (13 services are lazy, passive or on-demand)
2015-07-06 17:53:41,573 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-07-06 17:53:41,573 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-07-06 17:53:41,574 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:60)
2015-07-06 17:53:41,574 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: Unable to create default deployment
2015-07-06 17:53:41,575 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.createDefaultDeployment(Container.java:336)
2015-07-06 17:53:41,575 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.deploy(Container.java:269)
2015-07-06 17:53:41,575 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:26)
2015-07-06 17:53:41,575 ERROR [stderr] (main) 	... 5 more
2015-07-06 17:53:41,576 ERROR [stderr] (main) java.lang.RuntimeException: Unable to create default deployment
2015-07-06 17:53:41,576 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.createDefaultDeployment(Container.java:336)
2015-07-06 17:53:41,578 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.deploy(Container.java:269)
2015-07-06 17:53:41,580 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:26)
2015-07-06 17:53:41,580 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-07-06 17:53:41,581 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-07-06 17:53:41,581 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-07-06 17:53:41,582 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-07-06 17:53:41,582 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:60)
^C2015-07-06 17:55:46,300 INFO  [org.jboss.as.server] (Thread-3) WFLYSRV0220: Server shutdown has been requested.
```

**Comment by bobmcwhirter** [comment]
I'm out for the week but can merge PRs. 

--

**Comment by eprogramming** [comment]
sorry, my fault, false alarm.
wf-swarm-examples updated, personal project updated, ( my mind guess wf-swarm updated but not )
