### ISSUE TITLE
Packaged JAR cannot execute without Maven Local wildfly-swarm-runtime-* artifacts

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#88]
Given I create a packaged JAR either with Gradle or Maven, followed by either
 1. Sending it to a system without the `wildfly-swarm-runtime-*` artifacts in Maven Local or
 2. Removing the `wildfly-swarm-runtime-*` artifacts from the build system's Maven Local

When I then execute that JAR, I will get this exception:
```
Exception in thread "main" org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/msc/main/module.xml
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.jboss.msc:jboss-msc:1.2.6.Final' (position: END_TAG seen ...s>\r\n        <artifact name="org.jboss.msc:jboss-msc:1.2.6.Final"/>... @34:63) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
	... 10 more
```
This is occuring on my Windows system where I have a `.m2` folder setup by IntelliJ/Netbeans.

Strangely enough, I do not get this error when I add the same exact JAR to a barebones Debian Docker image that completely lacks any sort of Maven Repo.

**Comment by thomasandersen77** [comment]
@amannm  Do you have an git repo so I can try and reproduce this error?

I think my [issue] (https://github.com/wildfly-swarm/wildfly-swarm/issues/82) had some of the same chractaristics .

**Comment by amannm** [comment]
If you take any of the official examples and apply one of those two steps on in a Windows environment, you'll get that error. It's probably something to do with the slash handling...

**Comment by mstahv** [comment]
I had the same issue. I had empty localRepository tag "<localRepository/>" in my maven settings. Removing that (or setting it explicitly) seems to fix the issue. I guess swarm reads that value but treats "" bit differently than Maven itself.

Don't ask me why I had the empty localRepository definition there. I have no idea.

**Comment by bobmcwhirter** [comment]
I think I've just fixed this in HEAD.  Might be worth trying.

**Comment by mstahv** [comment]
Just tried with empty localRepository tag and it now works with that as well. Thanks.
