### ISSUE TITLE
JTDS driver classloading issue

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#91]
I setup most of my projects with a JTDS connection to SQL Server in `main`

        //deploy driver
        DriverDeployment driverDeployment = new DriverDeployment(container, "net.sourceforge.jtds:jtds:1.3.1", "jtds");
        container.deploy(driverDeployment);

        //deploy datasource
        Datasource datasource = new Datasource("prodmssql").connectionURL("jdbc:jtds:sqlserver://server.corp.test.com:1433;domain=MYDOMAIN").driver("jtds").authentication("myUsername", "myPassword");
        DatasourceDeployment dsDeployment = new DatasourceDeployment(container, datasource);
        container.deploy(dsDeployment);

However my projects sometimes get into a "funk" seemingly at random and start complaining about a missing JTDS library class:

	IJ000604: Throwable while attempting to get a new connection: null
	javax.resource.ResourceException: IJ031084: Unable to create connection
		at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:336)
		at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:343)
		at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:278)
		at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:1224)
		at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:484)
		at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:622)
		at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:594)
		at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:579)
		at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:430)
		at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:737)
		at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
		at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:67)
		at com.yodle.service.leadtargeting.dao.TargetDao.getTarget(TargetDao.java:91)
		at com.yodle.service.leadtargeting.orchestrator.TargetingOrchestrator.get(TargetingOrchestrator.java:44)
		at com.yodle.service.leadtargeting.endpoint.TargetingResource.createTarget(TargetingResource.java:92)
		at com.yodle.service.leadtargeting.endpoint.TargetingResource$Proxy$_$$_WeldClientProxy.createTarget(Unknown Source)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
		at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
		at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
		at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
		at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
		at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
		at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
		at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
		at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
		at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
		at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
		at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
		at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
		at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
		at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
		at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
		at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
		at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
		at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
		at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
		at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
		at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
		at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
		at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
		at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
		at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
		at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
		at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
		at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
		at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
		at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Jul 18, 2015 10:00:42 PM org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool getConnection
	Caused by: java.lang.NoClassDefFoundError: net/sourceforge/jtds/jdbc/CharsetInfo
		at net.sourceforge.jtds.jdbc.JtdsConnection.loadCharset(JtdsConnection.java:1453)
		at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:352)
		at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
		at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:312)
		... 56 more
	Caused by: java.lang.ClassNotFoundException: net.sourceforge.jtds.jdbc.CharsetInfo from [Module "deployment.jtds:main" from Service Module Loader]
		at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
		at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
		at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
		at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
		at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
		... 60 more

In this situation, the class is `net.sourceforge.jtds.jdbc.CharsetInfo` in other situations it is other *completely random* classes inside the JTDS library.

Usually when I run into this I just go work on something else and try again the next day and it magically works. Race condition in JBoss Modules?

**Comment by kenfinnigan** [comment]
Is your project available for us to test with?

**Comment by amannm** [comment]
The archive deployment methodology has drastically changed. Closing this out of date issue.
