### ISSUE TITLE
ModuleNotFoundException: org.jboss.logmanager:main

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-swarm#93]
When buildung the recent master I get this:

```
testSimple(org.wildfly.swarm.integration.jaxrs.JAXRSTest)  Time elapsed: 0.205 sec  <<< ERROR!
org.jboss.modules.ModuleNotFoundException: org.jboss.logmanager:main
	at org.jboss.modules.Module.addExportedPaths(Module.java:1193)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1227)
	at org.jboss.modules.Module.addPaths(Module.java:1071)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
	at org.wildfly.swarm.container.Container.createServer(Container.java:71)
	at org.wildfly.swarm.container.Container.<init>(Container.java:53)
	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:20)
	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:16)
	at org.wildfly.swarm.integration.jaxrs.JAXRSTest.testSimple(JAXRSTest.java:18)
```

**Comment by kenfinnigan** [comment]
Just tried myself and didn't hit that issue.

Any thoughts @jamezp ?

**Comment by bobmcwhirter** [comment]
Jdk8 is require. We see this with jdk7 I think. 

--

**Comment by heiko-braun** [comment]
I am running JDK8 (the enforcer plugin also verifies this):

hbraun:~/dev/prj/wildfly-swarm (master)$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**Comment by heiko-braun** [comment]
Hm, something is in flux. On a different run (CI machine this time) I get a related, but slightly different error:

```
testSimpleWithStatic(org.wildfly.swarm.integration.jaxrs.JAXRSTest)  Time elapsed: 0.363 sec  <<< ERROR!
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] org.jboss.modules.ModuleLoadException: Error loading module from modules/org/wildfly/swarm/runtime/container/main/module.xml
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:756)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:650)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleXmlParserBridge.parseModuleXml(ModuleXmlParserBridge.java:17)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:35)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:234)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.container.Container.createServer(Container.java:71)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.container.Container.<init>(Container.java:53)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:20)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.integration.base.AbstractWildFlySwarmTestCase.newContainer(AbstractWildFlySwarmTestCase.java:16)
[14:17:34][org.wildfly.swarm:wildfly-swarm-integration-tests-jaxrs] 	at org.wildfly.swarm.integration.jaxrs.JAXRSTest.testSimpleWithStatic(JAXRSTest.java:32)
```

**Comment by bobmcwhirter** [comment]
This is strange. Once I'm online I'll give you access to our CI machine also. 

--

**Comment by heiko-braun** [comment]
Do you have any build constraints other then JDK 8 and maven 3.2?

**Comment by bobmcwhirter** [comment]
Not that I’m aware of.


eduardo:wildfly-swarm bob$ java -version
java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b20)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b23, mixed mode)



eduardo:wildfly-swarm bob$ mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T12:29:23-05:00)
Maven home: /Users/bob/packages/apache-maven
Java version: 1.8.0_40-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
eduardo:wildfly-swarm bob$

**Comment by jamezp** [comment]
I'm not sure what this could be. I tested on 1.8.0_05 and didn't have any issues locally.

**Comment by heiko-braun** [comment]
@jamezp I don't think specific to the logging module. it just happens to be the only one bootstrapped by the container used in the test cases.

**Comment by jamezp** [comment]
Yeah it has to me something with how modules are being loaded.

**Comment by heiko-braun** [comment]
Todays build pulled in a set of snapshot dependencies and the problem disappeared. I consider this an intermittent test failure and close this issue.
